"""Initial migration

Revision ID: ca1b2ae60f63
Revises: 
Create Date: 2024-09-11 17:59:30.890693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1b2ae60f63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros',
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=True),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=150), nullable=True),
    sa.Column('numero_contacto', sa.String(length=15), nullable=True),
    sa.Column('lugar_votacion', sa.String(length=100), nullable=True),
    sa.Column('mesa_votacion', sa.String(length=20), nullable=True),
    sa.Column('tipo_transporte', sa.String(length=50), nullable=True),
    sa.Column('otro_transporte', sa.String(length=50), nullable=True),
    sa.Column('responsable', sa.String(length=2), nullable=True),
    sa.Column('codigo_responsable', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('cedula')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros')
    # ### end Alembic commands ###
